table ft_Consorcios
	lineageTag: afbaba87-e0ee-4f60-b5ae-7789ff08ab8b

	column #Nome_da_Administradora
		dataType: string
		lineageTag: c3280d08-8837-43ef-ac5e-c50c6b7d592b
		summarizeBy: none
		sourceColumn: #Nome_da_Administradora

		annotation SummarizationSetBy = Automatic

	column CNPJ_da_Administradora
		dataType: int64
		formatString: 0
		lineageTag: 2133f566-e174-4c34-bf82-36b6e198d06e
		summarizeBy: sum
		sourceColumn: CNPJ_da_Administradora

		annotation SummarizationSetBy = Automatic

	column Código_do_segmento
		dataType: int64
		formatString: 0
		lineageTag: 7f1334f3-dfe5-4da3-b9f3-9a4273775d42
		summarizeBy: sum
		sourceColumn: Código_do_segmento

		annotation SummarizationSetBy = Automatic

	column Taxa_de_administração
		dataType: double
		lineageTag: 19ad4a1f-fa11-42e8-ad95-b186699d6655
		summarizeBy: sum
		sourceColumn: Taxa_de_administração

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantidade_de_grupos_ativos
		dataType: int64
		formatString: 0
		lineageTag: bc4617cd-65da-495e-823c-692ceeea00da
		summarizeBy: sum
		sourceColumn: Quantidade_de_grupos_ativos

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_comercializadas_no_mês
		dataType: int64
		formatString: 0
		lineageTag: 13f67200-583d-4436-9c50-b41d12dacd0e
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_comercializadas_no_mês

		annotation SummarizationSetBy = Automatic

	column Quantidade_acumulada_de_cotas_ativas_contempladas
		dataType: int64
		formatString: 0
		lineageTag: 91571997-b32d-4acd-8ff7-a18dea9c286d
		summarizeBy: sum
		sourceColumn: Quantidade_acumulada_de_cotas_ativas_contempladas

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_não_contempladas
		dataType: int64
		formatString: 0
		lineageTag: 198845f3-2be2-46e3-851c-98e3f7c7e6d2
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_não_contempladas

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_contempladas_no_mês
		dataType: int64
		formatString: 0
		lineageTag: 197fa50d-901c-477b-80ac-ac5e52339c55
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_contempladas_no_mês

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_em_dia
		dataType: int64
		formatString: 0
		lineageTag: 4350ebab-68c7-4ba0-a685-325feaecfc87
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_em_dia

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_contempladas_inadimplentes
		dataType: int64
		formatString: 0
		lineageTag: 778fec29-3a65-4ffe-9e72-61adc8367d8c
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_contempladas_inadimplentes

		annotation SummarizationSetBy = Automatic

	column Quantidade_de_cotas_ativas_não_contempladas_inadimplentes
		dataType: int64
		formatString: 0
		lineageTag: 61e28e0d-a195-444e-9927-6e4275000500
		summarizeBy: sum
		sourceColumn: Quantidade_de_cotas_ativas_não_contempladas_inadimplentes

		annotation SummarizationSetBy = Automatic

	column 'Data Base'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 7ec32f7d-5014-47f9-8792-a6f98012c314
		summarizeBy: none
		sourceColumn: Data Base

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition ft_Consorcios = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(Caminho & Base), null, true),
				    SegmentosExtraidos_Table = Source{[Item="SegmentosExtraidos",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(SegmentosExtraidos_Table, "Data Base", each "01/" & Text.End(Text.From([Data_base]),2) & "/" & Text.Start(Text.From([Data_base]),4)),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Data_base"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"#Nome_da_Administradora", type text}, {"CNPJ_da_Administradora", Int64.Type}, {"Código_do_segmento", Int64.Type}, {"Taxa_de_administração", type number}, {"Quantidade_de_grupos_ativos", Int64.Type}, {"Quantidade_de_cotas_comercializadas_no_mês", Int64.Type}, {"Quantidade_acumulada_de_cotas_ativas_contempladas", Int64.Type}, {"Quantidade_de_cotas_ativas_não_contempladas", Int64.Type}, {"Quantidade_de_cotas_ativas_contempladas_no_mês", Int64.Type}, {"Quantidade_de_cotas_ativas_em_dia", Int64.Type}, {"Quantidade_de_cotas_ativas_contempladas_inadimplentes", Int64.Type}, {"Quantidade_de_cotas_ativas_não_contempladas_inadimplentes", Int64.Type}, {"Data Base", type date}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Changed Type",{"Quantidade_de_cotas_ativas_com_crédito_pendente_de_utilização", "Quantidade_de_cotas_ativas_quitadas", "Quantidade_de_cotas_excluídas", "Quantidade_de_cotas_excluídas_a_comercializar", "Quantidade_de_grupos_constituídos_no_mês", "Quantidade_de_grupos_encerrados_no_mês"}, MissingField.Ignore)
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

